services:
  mongo_primary:
    image: mongo
    container_name: mongo_primary
    restart: always
    volumes:
      - ./primary/data:/data/db
    command:  mongod --port 27017 --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - mongo_cluster
  mongo_s1:
    image: mongo
    container_name: mongo_s1
    restart: always
    volumes:
      - ./s1/data:/data/db
    command:  mongod --port 27017 --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - mongo_cluster
  mongo_s2:
    image: mongo
    container_name: mongo_s2
    restart: always
    volumes:
      - ./s2/data:/data/db
    command:  mongod --port 27017 --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - mongo_cluster

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5000:8081
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo_primary:27017/
    networks:
      - mongo_cluster

  export_primary:
    image: bitnami/mongodb-exporter:latest
    container_name: export_primary_c
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo_primary:27017/
    ports:
      - 9216:9216
    depends_on:
      - mongo_primary
    volumes:
      - ./mongo_exporter/primary:/data/exporter/primary
    networks:
      - mongo_cluster
  export_s1:
    image: bitnami/mongodb-exporter:latest
    container_name: export_s1_c
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo_s1:27017/
    ports:
      - 9217:9216
    depends_on:
      - mongo_s1
    volumes:
      - ./mongo_exporter/s1:/data/exporter/s1
    networks:
      - mongo_cluster
  export_s2:
    image: bitnami/mongodb-exporter:latest
    container_name: export_s2_c
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo_s2:27017/
    ports:
      - 9218:9216
    depends_on:
      - mongo_s2
    volumes:
      - ./mongo_exporter/s2:/data/exporter/s2
    networks:
      - mongo_cluster

networks:
  mongo_cluster:
    external: true


volumes:
  mongo_primary:
  mongo_s1:
  mongo_s2:

# Instruction:
#     docker exec -it "container_name" mongosh
#     rs.status()
    # var config = {
    #   _id: "rs0", "version": 1,
    #   members: [
    #     { _id: 1, host: "mongo_primary:27017", "priority": 3 },
    #     { _id: 2, host: "mongo_s1:27017", "priority": 2 },
    #     { _id: 3, host: "mongo_s2:27017", "priority": 1 }
    #   ]
    # };